project:
  type: website

website:
  title: "HPO_api_search"
  navbar:
    left:
      - href: README.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

